begin;
create extension if not exists pgtap with schema extensions;
select extensions.no_plan();
select extensions.has_type('public','quiz_assessment_mode','assessment mode exists');
select extensions.is((select array_agg(enumlabel::text order by enumsortorder) from pg_enum where enumtypid='public.quiz_assessment_mode'::regtype),array['QUICK_TOTAL','OUTCOME_DETAILED'],'assessment modes are closed');
select extensions.has_type('public','progression_evidence_state','evidence state exists');
select extensions.has_table('public','learning_outcomes','outcome identity exists');
select extensions.has_table('public','learning_outcome_revisions','immutable revisions exist');
select extensions.has_table('public','class_course_outcomes','year-specific usage exists');
select extensions.has_table('public','assessment_elements','assessment elements exist');
select extensions.has_table('public','assessment_element_outcomes','weighted links exist');
select extensions.has_table('public','student_element_scores','element evidence exists');
select extensions.has_column('public','quizzes','assessment_mode','quiz mode is explicit');
select extensions.has_column('public','quizzes','is_finalized','finalization is explicit');
select extensions.is((select column_default from information_schema.columns where table_schema='public' and table_name='quizzes' and column_name='assessment_mode'),'''QUICK_TOTAL''::quiz_assessment_mode','existing quizzes remain quick total');
select extensions.ok((select bool_and(relrowsecurity) from pg_class where oid in('public.learning_outcomes'::regclass,'public.learning_outcome_revisions'::regclass,'public.class_course_outcomes'::regclass,'public.assessment_elements'::regclass,'public.assessment_element_outcomes'::regclass,'public.student_element_scores'::regclass)),'all outcome tables use RLS');
select extensions.ok(not has_table_privilege('authenticated','public.learning_outcomes','insert,update,delete'),'catalog has no direct mutations');
select extensions.ok(not has_table_privilege('authenticated','public.assessment_elements','insert,update,delete'),'elements have no direct mutations');
select extensions.ok(not has_table_privilege('authenticated','public.student_element_scores','insert,update,delete'),'scores have no direct mutations');
select extensions.ok(to_regprocedure('public.create_learning_outcome(uuid,text,text,text)') is not null,'ADMIN create RPC exists');
select extensions.ok(to_regprocedure('public.publish_learning_outcome_revision(uuid,text,text)') is not null,'immutable revision RPC exists');
select extensions.ok(to_regprocedure('public.assign_outcome_revision(uuid,uuid)') is not null,'ClassCourse revision RPC exists');
select extensions.ok(to_regprocedure('public.upsert_assessment_element(uuid,uuid,integer,text,numeric)') is not null,'element RPC exists');
select extensions.ok(to_regprocedure('public.set_element_outcome_link(uuid,uuid,numeric,boolean)') is not null,'weighted link RPC exists');
select extensions.ok(to_regprocedure('public.save_student_element_scores(uuid,uuid,uuid[],numeric[])') is not null,'score RPC exists');
select extensions.ok(to_regprocedure('public.configure_detailed_quiz(uuid,boolean)') is not null,'detailed quiz lifecycle RPC exists');
select extensions.ok(to_regprocedure('public.learning_outcome_progression(uuid,uuid)') is not null,'dynamic progression projection exists');
select extensions.ok(has_function_privilege('authenticated','public.learning_outcome_progression(uuid,uuid)','execute'),'authenticated role may reach protected projection');
select extensions.ok(not has_function_privilege('anon','public.learning_outcome_progression(uuid,uuid)','execute'),'anonymous role cannot reach progression');
select extensions.is((select provolatile::text from pg_proc where oid='public.learning_outcome_progression(uuid,uuid)'::regprocedure),'s','progression is stable and derived');
select extensions.matches(pg_get_functiondef('public.learning_outcome_progression(uuid,uuid)'::regprocedure),'quizzes<2','two quizzes are required for a band');
select extensions.matches(pg_get_functiondef('public.learning_outcome_progression(uuid,uuid)'::regprocedure),'qc.score_total=qc.final_score','element and final totals must reconcile');
select extensions.matches(pg_get_functiondef('public.learning_outcome_progression(uuid,uuid)'::regprocedure),'OUTCOME_DETAILED','QUICK_TOTAL evidence is excluded');
select * from extensions.finish();
rollback;
