import"server-only";import{createServerSupabaseClient}from"@/lib/supabase/server";import{resolveApplicationContext}from"@/server/application-context";import{validAssignmentId}from"@/features/teacher-assignments/assignment";
export type MyClass=Readonly<{id:string;className:string;courseName:string;courseCode:string|null;schoolYear:string;allocatedPeriods:number;totalPeriods:number}>;
export type RosterStudent=Readonly<{id:string;firstName:string;lastName:string;code:string|null;startsOn:string;endsOn:string|null}>;
export type MyClassDetail=MyClass&Readonly<{students:readonly RosterStudent[]}>;
type Failure=Readonly<{status:"unauthenticated"|"forbidden"|"access-unavailable"|"error"}>;
async function context(){const access=await resolveApplicationContext();if(access.status==="unauthenticated")return{status:"unauthenticated"as const};if(access.status!=="ready")return{status:"access-unavailable"as const};if(access.context.role!=="TEACHER")return{status:"forbidden"as const};return{status:"ready"as const,userId:access.context.userId,supabase:await createServerSupabaseClient()};}
function map(row:{weekly_periods:number;class_courses:{id:string;class_id:string;weekly_periods:number;classes:{name:string;school_years:{label:string}};courses:{name:string;code:string|null}}}):MyClass{return{id:row.class_courses.id,className:row.class_courses.classes.name,courseName:row.class_courses.courses.name,courseCode:row.class_courses.courses.code,schoolYear:row.class_courses.classes.school_years.label,allocatedPeriods:row.weekly_periods,totalPeriods:row.class_courses.weekly_periods};}
const select="weekly_periods, class_courses!teacher_assignments_class_course_school_fk(id, class_id, weekly_periods, classes!class_courses_class_school_year_fk(name, school_years!classes_school_year_school_fk(label)), courses!class_courses_course_school_fk(name, code))" as const;
export async function listMyClasses():Promise<Readonly<{status:"ready";classes:readonly MyClass[]}>|Failure>{try{const ctx=await context();if(ctx.status!=="ready")return ctx;const result=await ctx.supabase.from("teacher_assignments").select(select).eq("teacher_id",ctx.userId).eq("is_active",true).order("created_at");if(result.error||!result.data)return{status:"error"};return{status:"ready",classes:result.data.map(map)};}catch{return{status:"error"};}}
export async function getMyClassDetail(id:string):Promise<Readonly<{status:"ready";value:MyClassDetail}>|Failure|Readonly<{status:"not-found"}>>{if(!validAssignmentId(id))return{status:"not-found"};try{const ctx=await context();if(ctx.status!=="ready")return ctx;const assignment=await ctx.supabase.from("teacher_assignments").select(select).eq("teacher_id",ctx.userId).eq("class_course_id",id).eq("is_active",true).maybeSingle();if(assignment.error)return{status:"error"};if(!assignment.data)return{status:"not-found"};const cc=assignment.data.class_courses;const enrollments=await ctx.supabase.from("enrollments").select("id, starts_on, ends_on, students!enrollments_student_school_fk(id, first_name, last_name, student_code)").eq("class_id",cc.class_id).is("ends_on",null).order("starts_on");if(enrollments.error||!enrollments.data)return{status:"error"};return{status:"ready",value:{...map(assignment.data),students:enrollments.data.map(row=>({id:row.students.id,firstName:row.students.first_name,lastName:row.students.last_name,code:row.students.student_code,startsOn:row.starts_on,endsOn:row.ends_on}))}};}catch{return{status:"error"};}}
