"use client";
import { useActionState, useEffect, useId, useRef } from "react";
import { useFormStatus } from "react-dom";
import { initialGradingActionState, type GradingActionState, type GradingMessage, type QuizSlot } from "./contracts";
import type { GradingQuiz, GradingStudent, GradingTerm } from "./data";

export type GradingFormMessages=Readonly<{term:string;semester1:string;semester2:string;slot:string;title:string;date:string;active:string;create:string;edit:string;save:string;saving:string;cancel:string;notEntered:string;score:string;results:Record<GradingMessage,string>}>;
type Action=(state:GradingActionState,data:FormData)=>Promise<GradingActionState>;
function Submit({m}:{m:GradingFormMessages}){const{pending}=useFormStatus();return <button className="structure-button structure-button--primary" disabled={pending}>{pending?m.saving:m.save}</button>;}
function Feedback({state,m}:{state:GradingActionState;m:GradingFormMessages}){if(!state.message)return null;return <p className={`structure-feedback structure-feedback--${state.status}`} role={state.status==="error"?"alert":"status"} tabIndex={-1}>{m.results[state.message]}</p>;}
function useFocus(state:GradingActionState){const ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.status==="error")ref.current?.querySelector<HTMLElement>('[aria-invalid="true"], [role="alert"]')?.focus();},[state]);return ref;}
const slotsFor=(semester:1|2):readonly QuizSlot[]=>semester===1?["C1","C2","C3","C4"]:["C5","C6","C7","C8"];

export function QuizForm({action,m,terms,quiz}:{action:Action;m:GradingFormMessages;terms:readonly GradingTerm[];quiz?:GradingQuiz}){const[state,formAction]=useActionState(action,initialGradingActionState);const id=useId();const ref=useFocus(state);const term=quiz?terms.find(t=>t.id===quiz.termId):terms[0];return <form action={formAction} className="structure-form" noValidate ref={ref}><Feedback state={state} m={m}/><div className="structure-field"><label htmlFor={`${id}-term`}>{m.term}</label><select defaultValue={term?.id} id={`${id}-term`} name="termId" required>{terms.map(t=><option key={t.id} value={t.id}>{t.semesterNumber===1?m.semester1:m.semester2}</option>)}</select></div><div className="structure-field"><label htmlFor={`${id}-slot`}>{m.slot}</label><select defaultValue={quiz?.slot??slotsFor(term?.semesterNumber??1)[0]} id={`${id}-slot`} name="slot" disabled={Boolean(quiz)}>{terms.flatMap(t=>slotsFor(t.semesterNumber)).map(slot=><option key={slot}>{slot}</option>)}</select>{quiz?<input name="slot" type="hidden" value={quiz.slot}/>:null}</div><div className="structure-field"><label htmlFor={`${id}-title`}>{m.title}</label><input defaultValue={quiz?.title} id={`${id}-title`} maxLength={160} name="title" required/></div><div className="structure-field"><label htmlFor={`${id}-date`}>{m.date}</label><input defaultValue={quiz?.quizDate} id={`${id}-date`} name="quizDate" required type="date"/></div>{quiz?<label><input name="isActive" type="hidden" value="false"/><input defaultChecked={quiz.isActive} name="isActive" type="checkbox" value="true"/> {m.active}</label>:null}<div className="structure-form__actions"><Submit m={m}/><button className="structure-button" onClick={e=>e.currentTarget.closest("details")?.removeAttribute("open")} type="button">{m.cancel}</button></div></form>;}

export function ScoreForm({action,m,quiz,students}:{action:Action;m:GradingFormMessages;quiz:GradingQuiz;students:readonly GradingStudent[]}){const[state,formAction]=useActionState(action,initialGradingActionState);const ref=useFocus(state);return <form action={formAction} className="grade-grid-form" ref={ref}><Feedback state={state} m={m}/><div className="grade-grid-scroll"><table><caption>{quiz.slot} — {quiz.title}</caption><thead><tr><th scope="col">#</th><th scope="col">{m.score}</th></tr></thead><tbody>{students.map((student,index)=><tr key={student.id}><th scope="row">{student.name}</th><td><input aria-label={`${student.name} — ${quiz.slot}`} defaultValue={student.scores[quiz.id]??""} inputMode="decimal" max="100" min="0" name={`score-${index}`} placeholder={m.notEntered} step="0.01" type="number"/></td></tr>)}</tbody></table></div><Submit m={m}/></form>;}
