import { cleanup, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { GradingClassesPage, GradingDetailPage, type GradingMessages } from "./pages";

vi.mock("./actions",()=>({createQuizAction:vi.fn(),updateQuizAction:vi.fn(),saveScoresAction:vi.fn()}));
const results={accessDenied:"Denied",invalidFields:"Invalid",invalidTitle:"Title",invalidDate:"Date",invalidScore:"Score",duplicateQuiz:"Duplicate",unavailable:"Unavailable",unexpected:"Unexpected",quizCreated:"Created",quizUpdated:"Updated",scoresSaved:"Saved",detailedConfigured:"Configured"} as const;
const m:GradingMessages={eyebrow:"Assessments",title:"Quizzes",description:"Shared",emptyClasses:"No authorized classes",open:"Open",back:"Back",noStudents:"No enrolled students",noQuizzes:"No quizzes",addQuiz:"Add quiz",term:"Term",semester1:"Semester 1",semester2:"Semester 2",slot:"Slot",date:"Date",active:"Active",create:"Create",edit:"Edit",save:"Save",saving:"Saving",cancel:"Cancel",notEntered:"Not entered",score:"Score",assessmentMode:"Mode",quickTotal:"Quick",outcomeDetailed:"Detailed",configureDetailed:"Configure",draft:"Draft",finalized:"Finalized",average:"Average",suggestion:"Oral suggestion",unavailable:"Unavailable",performance:{EXCELLENT:"Excellent",GOOD:"Good",AVERAGE:"Average",NEEDS_REINFORCEMENT:"Reinforcement"},results};
const classroom={id:"11111111-1111-4111-8111-111111111111",className:"Class A",courseName:"French",courseCode:"FRA",schoolYear:"2040–2041"} as const;
afterEach(cleanup);
describe("grading presentation",()=>{
  it("keeps authorized class links localized without printing identifiers",()=>{const{container}=render(<GradingClassesPage classes={[classroom]} locale="tr" m={m}/>);expect(screen.getByRole("link",{name:"Open"})).toHaveAttribute("href",`/tr/app/quiz-et-notes/${classroom.id}`);expect(container).not.toHaveTextContent(classroom.id);});
  it("shows an honest student and quiz empty state",()=>{render(<GradingDetailPage locale="fr" m={m} value={{...classroom,terms:[{id:"22222222-2222-4222-8222-222222222222",semesterNumber:1,startDate:"2040-09-01",endDate:"2041-01-31"}],quizzes:[],students:[]}}/>);expect(screen.getAllByText("No enrolled students").length).toBeGreaterThan(0);expect(screen.getByText("No quizzes")).toBeInTheDocument();expect(screen.queryByRole("textbox",{name:/Score/})).not.toBeInTheDocument();});
  it("filters slots by semester and excludes occupied slots",async()=>{const user=userEvent.setup();render(<GradingDetailPage locale="fr" m={m} value={{...classroom,terms:[{id:"22222222-2222-4222-8222-222222222222",semesterNumber:1,startDate:"2040-09-01",endDate:"2041-01-31"},{id:"33333333-3333-4333-8333-333333333333",semesterNumber:2,startDate:"2041-02-01",endDate:"2041-06-30"}],quizzes:[{id:"44444444-4444-4444-8444-444444444444",termId:"22222222-2222-4222-8222-222222222222",slot:"C1",title:"Existing",quizDate:"2040-10-01",isActive:true,assessmentMode:"QUICK_TOTAL",isFinalized:false}],students:[]}}/>);const summary=screen.getByText("Add quiz");await user.click(summary);const details=summary.closest("details");expect(details).not.toBeNull();const form=within(details!);const term=form.getByRole("combobox",{name:"Term"});expect(form.getByRole("combobox",{name:"Slot"})).not.toHaveTextContent("C1");expect(form.getByRole("combobox",{name:"Slot"})).toHaveTextContent("C2");expect(form.getByRole("combobox",{name:"Slot"})).not.toHaveTextContent("C5");await user.selectOptions(term,"33333333-3333-4333-8333-333333333333");expect(form.getByRole("combobox",{name:"Slot"})).toHaveTextContent("C5");expect(form.getByRole("combobox",{name:"Slot"})).not.toHaveTextContent("C2");});
});
