import { beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({revalidatePath:vi.fn(),redirect:vi.fn(),resolveApplicationContext:vi.fn(),createServerSupabaseClient:vi.fn()}));
vi.mock("next/cache",()=>({revalidatePath:mocks.revalidatePath}));vi.mock("next/navigation",()=>({redirect:mocks.redirect}));vi.mock("@/server/application-context",()=>({resolveApplicationContext:mocks.resolveApplicationContext}));vi.mock("@/lib/supabase/server",()=>({createServerSupabaseClient:mocks.createServerSupabaseClient}));
import { closeEnrollmentAction,createStudentAction,transferStudentAction,updateStudentAction } from "./actions";
import { initialStudentActionState } from "./student-workflows";
function form(entries:Record<string,string>){const data=new FormData();for(const[key,value]of Object.entries(entries))data.set(key,value);return data;}
const admin={status:"ready",context:{userId:"admin",role:"ADMIN",school:{id:"trusted-school",name:"School"}}};const studentId="11111111-1111-4111-8111-111111111111";const classId="22222222-2222-4222-8222-222222222222";
beforeEach(()=>{vi.clearAllMocks();mocks.resolveApplicationContext.mockResolvedValue(admin);});
describe("student Server Actions",()=>{
  it("creates exclusively through the atomic RPC with normalized input",async()=>{const rpc=vi.fn().mockResolvedValue({data:studentId,error:null});mocks.createServerSupabaseClient.mockResolvedValue({rpc});await createStudentAction("fr",initialStudentActionState,form({firstName:" Ada ",lastName:" Martin ",studentCode:" A-1 ",classId,startsOn:"2026-09-14"}));expect(rpc).toHaveBeenCalledWith("admin_create_student_with_enrollment",{student_first_name:"Ada",student_last_name:"Martin",student_code:"A-1",target_class_id:classId,enrollment_starts_on:"2026-09-14"});expect(mocks.redirect).toHaveBeenCalledWith(`/fr/app/eleves/${studentId}`);});
  it("rejects TEACHER inside the action",async()=>{mocks.resolveApplicationContext.mockResolvedValue({...admin,context:{...admin.context,role:"TEACHER"}});expect(await updateStudentAction(studentId,initialStudentActionState,form({firstName:"Ada",lastName:"Martin",studentCode:""}))).toMatchObject({message:"accessDenied"});});
  it("updates only identity through the typed RPC while preserving active state",async()=>{const rpc=vi.fn().mockResolvedValue({error:null});const query={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:{is_active:false},error:null})};query.select.mockReturnValue(query);query.eq.mockReturnValue(query);mocks.createServerSupabaseClient.mockResolvedValue({rpc,from:vi.fn(()=>query)});expect(await updateStudentAction(studentId,initialStudentActionState,form({firstName:" Ada ",lastName:" Martin ",studentCode:""}))).toEqual({status:"success",message:"studentUpdated"});expect(rpc).toHaveBeenCalledWith("admin_update_student",expect.objectContaining({target_student_id:studentId,student_is_active:false}));});
  it("requires confirmation before transfer RPC",async()=>{const result=await transferStudentAction(studentId,initialStudentActionState,form({classId,transferDate:"2026-10-01"}));expect(result).toMatchObject({status:"error",fieldErrors:{confirmation:"confirmationRequired"}});expect(mocks.createServerSupabaseClient).not.toHaveBeenCalled();});
  it("transfers with exact RPC arguments",async()=>{const rpc=vi.fn().mockResolvedValue({data:"33333333-3333-4333-8333-333333333333",error:null});mocks.createServerSupabaseClient.mockResolvedValue({rpc});expect(await transferStudentAction(studentId,initialStudentActionState,form({classId,transferDate:"2026-10-01",confirmation:"on"}))).toEqual({status:"success",message:"transferComplete"});expect(rpc).toHaveBeenCalledWith("admin_transfer_student",{target_student_id:studentId,target_class_id:classId,transfer_date:"2026-10-01"});});
  it("closes through the RPC only after confirmation",async()=>{const rpc=vi.fn().mockResolvedValue({error:null});mocks.createServerSupabaseClient.mockResolvedValue({rpc});expect(await closeEnrollmentAction(studentId,initialStudentActionState,form({endDate:"2026-10-31",confirmation:"on"}))).toEqual({status:"success",message:"closeComplete"});expect(rpc).toHaveBeenCalledWith("admin_close_current_enrollment",{target_student_id:studentId,enrollment_end_date:"2026-10-31"});});
  it("never returns raw provider errors",async()=>{const rpc=vi.fn().mockResolvedValue({error:{code:"P0001",message:"foreign tenant identifier"}});const query={select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:{is_active:true},error:null})};query.select.mockReturnValue(query);query.eq.mockReturnValue(query);mocks.createServerSupabaseClient.mockResolvedValue({rpc,from:vi.fn(()=>query)});expect(await updateStudentAction(studentId,initialStudentActionState,form({firstName:"Ada",lastName:"Martin",studentCode:""}))).toEqual({status:"error",message:"studentUnavailable"});});
});
