"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { isLocale,type Locale } from "@/i18n/routing";
import { resolveApplicationContext } from "@/server/application-context";
import { mapStudentError,parseCloseEnrollment,parseCreateStudent,parseTransferStudent,parseUpdateStudent,validStudentId,type StudentActionState } from "./student-workflows";

async function context(){const access=await resolveApplicationContext();if(access.status!=="ready"||access.context.role!=="ADMIN")return null;return{schoolId:access.context.school.id,supabase:await createServerSupabaseClient()};}
function refresh(id?:string){for(const locale of ["fr","tr"] as const){revalidatePath(`/${locale}/app/eleves`);if(id)revalidatePath(`/${locale}/app/eleves/${id}`);}}
export async function createStudentAction(locale:Locale,_:StudentActionState,formData:FormData):Promise<StudentActionState>{if(!isLocale(locale))return{status:"error",message:"accessDenied"};const parsed=parseCreateStudent(formData);if(!parsed.ok)return parsed.state;let id:string|undefined;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const result=await ctx.supabase.rpc("admin_create_student_with_enrollment",{student_first_name:parsed.data.firstName,student_last_name:parsed.data.lastName,student_code:parsed.data.studentCode,target_class_id:parsed.data.classId,enrollment_starts_on:parsed.data.startsOn});if(result.error||!result.data)return{status:"error",message:mapStudentError(result.error)};id=result.data;refresh(id);}catch{return{status:"error",message:"unexpected"};}redirect(`/${locale}/app/eleves/${id}`);}
export async function updateStudentAction(studentId:string,_:StudentActionState,formData:FormData):Promise<StudentActionState>{if(!validStudentId(studentId))return{status:"error",message:"studentUnavailable"};const parsed=parseUpdateStudent(formData);if(!parsed.ok)return parsed.state;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const existing=await ctx.supabase.from("students").select("is_active").eq("id",studentId).eq("school_id",ctx.schoolId).maybeSingle();if(existing.error||!existing.data)return{status:"error",message:"studentUnavailable"};const result=await ctx.supabase.rpc("admin_update_student",{target_student_id:studentId,student_first_name:parsed.data.firstName,student_last_name:parsed.data.lastName,student_code:parsed.data.studentCode,student_is_active:existing.data.is_active});if(result.error)return{status:"error",message:mapStudentError(result.error)};refresh(studentId);return{status:"success",message:"studentUpdated"};}catch{return{status:"error",message:"unexpected"};}}
export async function transferStudentAction(studentId:string,_:StudentActionState,formData:FormData):Promise<StudentActionState>{if(!validStudentId(studentId))return{status:"error",message:"studentUnavailable"};const parsed=parseTransferStudent(formData);if(!parsed.ok)return parsed.state;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const result=await ctx.supabase.rpc("admin_transfer_student",{target_student_id:studentId,target_class_id:parsed.data.classId,transfer_date:parsed.data.transferDate});if(result.error)return{status:"error",message:mapStudentError(result.error)};refresh(studentId);return{status:"success",message:"transferComplete"};}catch{return{status:"error",message:"unexpected"};}}
export async function closeEnrollmentAction(studentId:string,_:StudentActionState,formData:FormData):Promise<StudentActionState>{if(!validStudentId(studentId))return{status:"error",message:"studentUnavailable"};const parsed=parseCloseEnrollment(formData);if(!parsed.ok)return parsed.state;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const result=await ctx.supabase.rpc("admin_close_current_enrollment",{target_student_id:studentId,enrollment_end_date:parsed.data.endDate});if(result.error)return{status:"error",message:mapStudentError(result.error)};refresh(studentId);return{status:"success",message:"closeComplete"};}catch{return{status:"error",message:"unexpected"};}}
