import "server-only";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { resolveApplicationContext } from "@/server/application-context";
import { validStudentId } from "./student-workflows";

export type StudentClassOption=Readonly<{id:string;name:string;schoolYearId:string;schoolYearLabel:string;schoolYearStart:string}>;
export type EnrollmentView=Readonly<{id:string;classId:string;className:string;schoolYearId:string;schoolYearLabel:string;startsOn:string;endsOn:string|null}>;
export type StudentSummary=Readonly<{id:string;firstName:string;lastName:string;studentCode:string|null;active:boolean;current:EnrollmentView|null}>;
export type StudentDetail=StudentSummary&Readonly<{history:readonly EnrollmentView[];transferClasses:readonly StudentClassOption[]}>;
type Status="unauthenticated"|"forbidden"|"access-unavailable"|"error";
export type StudentListResult=Readonly<{status:"ready";students:readonly StudentSummary[];classes:readonly StudentClassOption[]}>|Readonly<{status:Status}>;
export type StudentDetailResult=Readonly<{status:"ready";student:StudentDetail}>|Readonly<{status:Status|"not-found"}>;

async function adminContext(){const access=await resolveApplicationContext();if(access.status==="unauthenticated")return {status:"unauthenticated" as const};if(access.status!=="ready")return {status:"access-unavailable" as const};if(access.context.role!=="ADMIN")return {status:"forbidden" as const};return {status:"ready" as const,schoolId:access.context.school.id,supabase:await createServerSupabaseClient()};}
function enrollment(row:{id:string;class_id:string;starts_on:string;ends_on:string|null;classes:{name:string;school_year_id:string;school_years:{label:string}}}):EnrollmentView{return{id:row.id,classId:row.class_id,className:row.classes.name,schoolYearId:row.classes.school_year_id,schoolYearLabel:row.classes.school_years.label,startsOn:row.starts_on,endsOn:row.ends_on};}
async function classes(context:Extract<Awaited<ReturnType<typeof adminContext>>,{status:"ready"}>):Promise<readonly StudentClassOption[]|null>{const result=await context.supabase.from("classes").select("id, name, school_year_id, school_years!classes_school_year_school_fk(label, start_date, active)").eq("school_id",context.schoolId).eq("is_active",true).order("name");if(result.error||!result.data)return null;return result.data.filter((row)=>row.school_years.active).map((row)=>({id:row.id,name:row.name,schoolYearId:row.school_year_id,schoolYearLabel:row.school_years.label,schoolYearStart:row.school_years.start_date}));}

export async function listStudents():Promise<StudentListResult>{try{const context=await adminContext();if(context.status!=="ready")return context;const [studentResult,enrollmentResult,classOptions]=await Promise.all([context.supabase.from("students").select("id, first_name, last_name, student_code, is_active").eq("school_id",context.schoolId).order("last_name").order("first_name"),context.supabase.from("enrollments").select("id, student_id, class_id, starts_on, ends_on, classes!enrollments_class_school_year_fk(name, school_year_id, school_years!classes_school_year_school_fk(label))").eq("school_id",context.schoolId).is("ends_on",null),classes(context)]);if(studentResult.error||enrollmentResult.error||!studentResult.data||!enrollmentResult.data||!classOptions)return{status:"error"};const current=new Map(enrollmentResult.data.map((row)=>[row.student_id,enrollment(row)]));return{status:"ready",classes:classOptions,students:studentResult.data.map((row)=>({id:row.id,firstName:row.first_name,lastName:row.last_name,studentCode:row.student_code,active:row.is_active,current:current.get(row.id)??null}))};}catch{return{status:"error"};}}

export async function getStudentDetail(studentId:string):Promise<StudentDetailResult>{if(!validStudentId(studentId))return{status:"not-found"};try{const context=await adminContext();if(context.status!=="ready")return context;const [studentResult,historyResult,classOptions]=await Promise.all([context.supabase.from("students").select("id, first_name, last_name, student_code, is_active").eq("id",studentId).eq("school_id",context.schoolId).maybeSingle(),context.supabase.from("enrollments").select("id, class_id, starts_on, ends_on, classes!enrollments_class_school_year_fk(name, school_year_id, school_years!classes_school_year_school_fk(label))").eq("student_id",studentId).eq("school_id",context.schoolId).order("starts_on",{ascending:false}),classes(context)]);if(studentResult.error||historyResult.error||!historyResult.data||!classOptions)return{status:"error"};if(!studentResult.data)return{status:"not-found"};const history=historyResult.data.map(enrollment);const current=history.find((item)=>item.endsOn===null)??null;return{status:"ready",student:{id:studentResult.data.id,firstName:studentResult.data.first_name,lastName:studentResult.data.last_name,studentCode:studentResult.data.student_code,active:studentResult.data.is_active,current,history,transferClasses:current?classOptions.filter((item)=>item.schoolYearId===current.schoolYearId&&item.id!==current.classId):[]}};}catch{return{status:"error"};}}

