"use client";
import { useActionState,useEffect,useId,useRef } from "react";
import { useFormStatus } from "react-dom";
import type { StudentClassOption,StudentDetail } from "./data";
import { initialStudentActionState,type StudentActionState,type StudentField } from "./student-workflows";
import type { StudentMessages } from "./messages";
type Action=(state:StudentActionState,data:FormData)=>Promise<StudentActionState>;
function Submit({m}:{m:StudentMessages}){const{pending}=useFormStatus();return <button className="student-button student-button--primary" disabled={pending} type="submit">{pending?m.form.saving:m.form.save}</button>;}
function Feedback({m,state}:{m:StudentMessages;state:StudentActionState}){return state.message?<p aria-live="polite" className={`student-feedback student-feedback--${state.status}`} role={state.status==="error"?"alert":"status"} tabIndex={-1}>{m.results[state.message]}</p>:null;}
function Field({children,error,field,label,id}:{children:React.ReactNode;error?:string;field:StudentField;label:string;id:string}){return <div className="student-field"><label htmlFor={`${id}-${field}`}>{label}</label>{children}{error?<p className="student-field__error" id={`${id}-${field}-error`}>{error}</p>:null}</div>;}
function Form({action,children,m}:{action:Action;children:(id:string,state:StudentActionState)=>React.ReactNode;m:StudentMessages}){const[state,formAction]=useActionState(action,initialStudentActionState);const id=useId();const ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.status==="error")ref.current?.querySelector<HTMLElement>('[aria-invalid="true"],.student-feedback')?.focus();},[state]);return <form action={formAction} className="student-form" noValidate ref={ref}><Feedback m={m} state={state}/>{children(id,state)}<div className="student-form__actions"><Submit m={m}/><button className="student-button" onClick={(event)=>event.currentTarget.closest("details")?.removeAttribute("open")} type="button">{m.form.cancel}</button></div></form>;}
function Input({defaultValue="",field,label,type="text",state,id,m}:{defaultValue?:string;field:StudentField;label:string;type?:string;state:StudentActionState;id:string;m:StudentMessages}){const error=state.fieldErrors?.[field];return <Field error={error?m.results[error]:undefined} field={field} id={id} label={label}><input aria-describedby={error?`${id}-${field}-error`:undefined} aria-invalid={Boolean(error)} autoComplete="off" defaultValue={defaultValue} id={`${id}-${field}`} name={field} required={field!=="studentCode"} type={type}/></Field>;}
function Confirmation({m,state}:{m:StudentMessages;state:StudentActionState}){const error=state.fieldErrors?.confirmation;return <div className="student-confirmation"><label><input aria-invalid={Boolean(error)} name="confirmation" required type="checkbox"/> {m.confirm}</label>{error?<p className="student-field__error">{m.results[error]}</p>:null}</div>;}
export function CreateStudentForm({action,classes,m}:{action:Action;classes:readonly StudentClassOption[];m:StudentMessages}){return <Form action={action} m={m}>{(id,state)=><><Input field="firstName" id={id} label={m.form.firstName} m={m} state={state}/><Input field="lastName" id={id} label={m.form.lastName} m={m} state={state}/><Input field="studentCode" id={id} label={m.form.studentCode} m={m} state={state}/><Field error={state.fieldErrors?.classId?m.results[state.fieldErrors.classId]:undefined} field="classId" id={id} label={m.form.className}><select aria-invalid={Boolean(state.fieldErrors?.classId)} defaultValue="" id={`${id}-classId`} name="classId" required><option disabled value="">—</option>{classes.map((item)=><option data-start={item.schoolYearStart} key={item.id} value={item.id}>{item.name} — {item.schoolYearLabel}</option>)}</select></Field><Input field="startsOn" id={id} label={m.form.startsOn} m={m} state={state} type="date"/></>}</Form>;}
export function EditStudentForm({action,m,student}:{action:Action;m:StudentMessages;student:StudentDetail}){return <Form action={action} m={m}>{(id,state)=><><Input defaultValue={student.firstName} field="firstName" id={id} label={m.form.firstName} m={m} state={state}/><Input defaultValue={student.lastName} field="lastName" id={id} label={m.form.lastName} m={m} state={state}/><Input defaultValue={student.studentCode??""} field="studentCode" id={id} label={m.form.studentCode} m={m} state={state}/></>}</Form>;}
export function TransferForm({action,classes,m}:{action:Action;classes:readonly StudentClassOption[];m:StudentMessages}){return <Form action={action} m={m}>{(id,state)=><><p>{m.transferHelp}</p><Field error={state.fieldErrors?.classId?m.results[state.fieldErrors.classId]:undefined} field="classId" id={id} label={m.form.className}><select aria-invalid={Boolean(state.fieldErrors?.classId)} defaultValue="" id={`${id}-classId`} name="classId" required><option disabled value="">—</option>{classes.map((item)=><option key={item.id} value={item.id}>{item.name} — {item.schoolYearLabel}</option>)}</select></Field><Input field="transferDate" id={id} label={m.form.transferDate} m={m} state={state} type="date"/><Confirmation m={m} state={state}/></>}</Form>;}
export function CloseForm({action,m}:{action:Action;m:StudentMessages}){return <Form action={action} m={m}>{(id,state)=><><p>{m.closeHelp}</p><Input field="endDate" id={id} label={m.form.endDate} m={m} state={state} type="date"/><Confirmation m={m} state={state}/></>}</Form>;}
