import Link from "next/link";
import { closeEnrollmentAction,createStudentAction,transferStudentAction,updateStudentAction } from "./actions";
import type { StudentClassOption,StudentDetail,StudentSummary } from "./data";
import { CloseForm,CreateStudentForm,EditStudentForm,TransferForm } from "./forms";
import type { StudentMessages } from "./messages";
import type { Locale } from "@/i18n/routing";
function formatDate(value:string,locale:Locale){return new Intl.DateTimeFormat(locale==="fr"?"fr-FR":"tr-TR",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));}
function Status({active,m}:{active:boolean;m:StudentMessages}){return <span className={`student-status student-status--${active?"active":"inactive"}`}><span aria-hidden="true">{active?"●":"○"}</span> {active?m.active:m.inactive}</span>;}
export function StudentsPage({classes,locale,m,readError,students,filters}:{classes:readonly StudentClassOption[];locale:Locale;m:StudentMessages;readError:boolean;students:readonly StudentSummary[];filters:{query:string;classId:string;status:string}}){const q=filters.query.trim().toLocaleLowerCase(locale);const visible=students.filter((student)=>(!q||`${student.firstName} ${student.lastName} ${student.studentCode??""}`.toLocaleLowerCase(locale).includes(q))&&(!filters.classId||student.current?.classId===filters.classId)&&(!filters.status||(filters.status==="active")===student.active));return <section className="student-page"><header className="student-page__header"><div><p className="student-page__eyebrow">{m.eyebrow}</p><h1>{m.title}</h1><p>{m.description}</p></div><details><summary>{m.add}</summary><CreateStudentForm action={createStudentAction.bind(null,locale)} classes={classes} m={m}/></details></header><form className="student-filters" method="get"><label><span>{m.search}</span><input defaultValue={filters.query} name="q" type="search"/></label><label><span>{m.currentClass}</span><select defaultValue={filters.classId} name="class"><option value="">{m.allClasses}</option>{classes.map((item)=><option key={item.id} value={item.id}>{item.name} — {item.schoolYearLabel}</option>)}</select></label><label><span>{m.allStatuses}</span><select defaultValue={filters.status} name="status"><option value="">{m.allStatuses}</option><option value="active">{m.active}</option><option value="inactive">{m.inactive}</option></select></label><button className="student-button" type="submit">{m.search}</button></form>{readError?<div className="student-empty" role="alert"><h2>{m.readErrorTitle}</h2><p>{m.readErrorDescription}</p></div>:students.length===0?<div className="student-empty"><h2>{m.emptyTitle}</h2><p>{m.emptyDescription}</p></div>:visible.length===0?<div className="student-empty"><p>{m.filteredEmpty}</p></div>:<div className="student-list">{visible.map((student)=><article className="student-card" key={student.id}><div><h2>{student.firstName} {student.lastName}</h2>{student.studentCode?<p>{student.studentCode}</p>:null}<Status active={student.active} m={m}/><p>{m.currentClass}: {student.current?.className??m.noCurrent}</p>{student.current?<p>{m.schoolYear}: {student.current.schoolYearLabel}</p>:null}</div><Link href={`/${locale}/app/eleves/${student.id}`}>{m.details}</Link></article>)}</div>}</section>;}
export function StudentDetailPage({locale,m,student}:{locale:Locale;m:StudentMessages;student:StudentDetail}){return <section className="student-page"><Link href={`/${locale}/app/eleves`}>← {m.back}</Link><header className="student-detail-header"><div><p className="student-page__eyebrow">{m.eyebrow}</p><h1>{student.firstName} {student.lastName}</h1>{student.studentCode?<p>{student.studentCode}</p>:null}<Status active={student.active} m={m}/></div><details><summary>{m.edit}</summary><EditStudentForm action={updateStudentAction.bind(null,student.id)} m={m} student={student}/></details></header><section className="student-current"><h2>{m.currentClass}</h2><p>{student.current?`${student.current.className} — ${student.current.schoolYearLabel}`:m.noCurrent}</p>{student.current?<div className="student-workflows">{student.transferClasses.length?<details><summary>{m.transfer}</summary><TransferForm action={transferStudentAction.bind(null,student.id)} classes={student.transferClasses} m={m}/></details>:null}<details><summary>{m.close}</summary><CloseForm action={closeEnrollmentAction.bind(null,student.id)} m={m}/></details></div>:null}</section><section><h2>{m.history}</h2><ol className="student-timeline">{student.history.map((item)=><li key={item.id}><h3>{item.className}</h3><p>{item.schoolYearLabel}</p><p>{formatDate(item.startsOn,locale)} — {item.endsOn?formatDate(item.endsOn,locale):m.current}</p><strong>{item.endsOn?m.closed:m.current}</strong></li>)}</ol></section></section>;}

