import Link from "next/link";
import { createClassAction, updateClassAction } from "./actions";
import { connectCourseAction, updatePeriodsAction } from "@/features/class-courses/actions";
import { ClassForm, ConnectionForm, PeriodsForm } from "@/features/class-courses/forms";
import type { ClassDetail, ClassSummary } from "./data";
import type { StructurePageMessages } from "@/features/class-courses/messages";
import type { Locale } from "@/i18n/routing";
import { createAssignmentAction,updateAssignmentAction } from "@/features/teacher-assignments/actions";
import { CreateAssignmentForm,UpdateAssignmentForm } from "@/features/teacher-assignments/forms";
import type { AssignmentMessages } from "@/features/teacher-assignments/messages";

function Status({ active, m }: {active:boolean;m:StructurePageMessages}) { return <span className="structure-status"><span aria-hidden="true">{active ? "●" : "○"}</span> {active ? m.active : m.inactive}</span>; }
export function ClassesPage({classes,locale,m,readError,years}:{classes:readonly ClassSummary[];locale:Locale;m:StructurePageMessages;readError:boolean;years:readonly {id:string;label:string}[]}) { return <section className="structure-page"><header className="structure-header"><div><p>{m.eyebrow}</p><h1>{m.title}</h1><p>{m.description}</p></div><details><summary>{m.add}</summary><ClassForm action={createClassAction} m={m.form} years={years}/></details></header>{readError?<div className="structure-empty" role="alert"><h2>{m.readErrorTitle}</h2><p>{m.readErrorDescription}</p></div>:classes.length===0?<div className="structure-empty"><h2>{m.emptyTitle}</h2><p>{m.emptyDescription}</p></div>:<div className="structure-list">{classes.map(c=><article className="structure-card" key={c.id}><div><h2>{c.name}</h2><p>{m.schoolYear}: {c.schoolYearLabel}</p><Status active={c.active} m={m}/>{!c.schoolYearActive?<Status active={false} m={m}/>:null}</div><div className="structure-card__actions"><Link href={`/${locale}/app/classes/${c.id}`}>{m.details}</Link><details><summary>{m.edit}</summary><ClassForm action={updateClassAction.bind(null,c.id)} initialName={c.name} m={m.form}/></details></div></article>)}</div>}</section>; }
export function ClassDetailPage({assignments:a,locale,m,value}:{assignments:AssignmentMessages;locale:Locale;m:StructurePageMessages;value:ClassDetail}) { return <section className="structure-page"><Link href={`/${locale}/app/classes`}>← {m.back}</Link><header className="structure-detail-header"><div><p>{m.schoolYear}: {value.schoolYearLabel}</p><h1>{value.name}</h1><Status active={value.active} m={m}/></div></header><section><h2>{m.connected}</h2>{value.connections.length===0?<p>{m.noConnections}</p>:<div className="structure-list">{value.connections.map(item=>{const remaining=item.weeklyPeriods-item.assignedPeriods;return <article className="structure-card structure-card--stack" key={item.id}><div><h3>{item.courseName}</h3>{item.courseCode?<p>{item.courseCode}</p>:null}<p>{m.periods}: {item.weeklyPeriods}</p><Status active={item.active} m={m}/></div><details><summary>{m.edit}</summary><PeriodsForm action={updatePeriodsAction.bind(null,value.id,item.id)} initial={item.weeklyPeriods} m={m.form}/></details><section className="assignment-section"><h4>{a.title}</h4><p>{a.assigned}: {item.assignedPeriods} · {a.remaining}: {remaining}</p>{item.assignments.length===0?<p>{a.none}</p>:<ul className="assignment-list">{item.assignments.map(x=><li key={x.id}><div><strong>{x.teacherName}</strong><span>{x.weeklyPeriods} · {x.active?a.active:a.inactive}</span></div><details><summary>{x.active?a.edit:a.reactivate}</summary><UpdateAssignmentForm action={updateAssignmentAction.bind(null,value.id,x.id,true)} active m={a} max={remaining+x.weeklyPeriods} value={x.weeklyPeriods}/></details>{x.active?<details><summary>{a.deactivate}</summary><UpdateAssignmentForm action={updateAssignmentAction.bind(null,value.id,x.id,false)} active={false} m={a} max={item.weeklyPeriods} value={x.weeklyPeriods}/></details>:null}</li>)}</ul>}{item.eligibleTeachers.length===0?<p>{a.noTeachers} <Link href={`/${locale}/app/enseignants`}>{a.manageTeachers}</Link></p>:remaining<1?<p>{a.results.capacityExceeded}</p>:<details><summary>{a.add}</summary><CreateAssignmentForm action={createAssignmentAction.bind(null,value.id,item.id)} m={a} max={remaining} teachers={item.eligibleTeachers}/></details>}</section></article>;})}</div>}</section><section className="structure-connect"><h2>{m.connect}</h2>{!value.active||value.eligibleCourses.length===0?<p>{m.noEligible}</p>:<ConnectionForm action={connectCourseAction.bind(null,value.id)} courses={value.eligibleCourses} m={m.form}/>}</section></section>; }
