"use client";import{useActionState,useId}from"react";import{useFormStatus}from"react-dom";import{finalizeDetailedQuizAction,linkOutcomeAction,saveDetailedScoresAction,saveElementAction}from"./actions";import{initialDetailedState,type DetailedMessage,type DetailedState}from"./contracts";
type M=Record<string,string>&{results:Record<DetailedMessage,string>};type Action=(s:DetailedState,d:FormData)=>Promise<DetailedState>;
function Submit({m,label}:{m:M;label?:string}){const{pending}=useFormStatus();return<button className="structure-button structure-button--primary"disabled={pending}>{pending?m.saving:label??m.save}</button>};function Feedback({s,m}:{s:DetailedState;m:M}){return s.message?<p role={s.status==="error"?"alert":"status"}>{m.results[s.message]}</p>:null}
function ActionForm({action,m,children,label}:{action:Action;m:M;children:React.ReactNode;label?:string}){const[s,a]=useActionState(action,initialDetailedState);return<form action={a}className="structure-form"><Feedback s={s}m={m}/>{children}<Submit m={m}label={label}/></form>}
export function ElementForm({cc,q,m,element}:{cc:string;q:string;m:M;element?:{id:string;position:number;title:string;maxPoints:number}}){const id=useId();return<ActionForm action={saveElementAction.bind(null,cc,q)}m={m}><input type="hidden"name="elementId"value={element?.id??""}/><label htmlFor={`${id}-position`}>{m.position}</label><input id={`${id}-position`}name="position"type="number"min="1"max="100"defaultValue={element?.position??1}required/><label htmlFor={`${id}-title`}>{m.elementTitle}</label><input id={`${id}-title`}name="title"maxLength={160}defaultValue={element?.title}required/><label htmlFor={`${id}-max`}>{m.maxPoints}</label><input id={`${id}-max`}name="maxPoints"type="number"min="0.01"max="100"step="0.01"defaultValue={element?.maxPoints??50}required/></ActionForm>}
export function LinkForm({cc,q,m,elementId,outcomes}:{cc:string;q:string;m:M;elementId:string;outcomes:readonly{id:string;code:string;title:string;revision:number}[]}){const id=useId();return<ActionForm action={linkOutcomeAction.bind(null,cc,q)}m={m}label={m.link}><input type="hidden"name="elementId"value={elementId}/><input type="hidden"name="active"value="true"/><label htmlFor={`${id}-outcome`}>{m.outcome}</label><select id={`${id}-outcome`}name="classCourseOutcomeId"required>{outcomes.map(o=><option key={o.id}value={o.id}>{o.code} · v{o.revision} · {o.title}</option>)}</select><label htmlFor={`${id}-weight`}>{m.weight}</label><input id={`${id}-weight`}name="weight"type="number"min="0.01"max="100"step="0.01"defaultValue="100"required/></ActionForm>}
export function UnlinkForm({cc,q,m,elementId,useId,weight}:{cc:string;q:string;m:M;elementId:string;useId:string;weight:number}){return<ActionForm action={linkOutcomeAction.bind(null,cc,q)}m={m}label={m.unlink}><input type="hidden"name="elementId"value={elementId}/><input type="hidden"name="classCourseOutcomeId"value={useId}/><input type="hidden"name="weight"value={weight}/><input type="hidden"name="active"value="false"/></ActionForm>}
export function DetailedScoreForm({cc,q,m,student,elements}:{cc:string;q:string;m:M;student:{id:string;name:string;scores:Record<string,number>;finalScore:number|null};elements:readonly{id:string;title:string;maxPoints:number}[]}){const action=saveDetailedScoresAction.bind(null,cc,q,student.id,elements.map(e=>({id:e.id,maxPoints:e.maxPoints})));return<ActionForm action={action}m={m}label={m.saveScores}><fieldset><legend>{student.name}</legend>{elements.map((e,i)=><label key={e.id}>{e.title} ({m.maximum} {e.maxPoints})<input aria-label={`${student.name} — ${e.title}`}name={`element-${i}`}type="number"min="0"max={e.maxPoints}step="0.01"defaultValue={student.scores[e.id]??""}placeholder={m.missing}/></label>)}<label>{m.finalScore}<input name="finalScore"type="number"min="0"max="100"step="0.01"defaultValue={student.finalScore??""}placeholder={m.missing}/></label></fieldset></ActionForm>}
export function FinalizeForm({cc,q,m}:{cc:string;q:string;m:M}){return<ActionForm action={finalizeDetailedQuizAction.bind(null,cc,q)}m={m}label={m.finalize}><label><input name="confirm"type="checkbox"value="true"required/> {m.confirmFinalize}</label></ActionForm>}
