"use server";
import{revalidatePath}from"next/cache";import{createServerSupabaseClient}from"@/lib/supabase/server";import{resolveApplicationContext}from"@/server/application-context";import{parseOutcomeForm,type ProgressionActionState}from"./contracts";
export async function createOutcomeAction(_:ProgressionActionState,data:FormData):Promise<ProgressionActionState>{const parsed=parseOutcomeForm(data);if(!parsed.ok)return{status:"error",message:"invalidFields"};const access=await resolveApplicationContext();if(access.status!=="ready"||access.context.role!=="ADMIN")return{status:"error",message:"accessDenied"};try{const client=await createServerSupabaseClient();const result=await client.rpc("create_learning_outcome",{target_course_id:parsed.data.courseId,outcome_code:parsed.data.code,outcome_title:parsed.data.title,outcome_description:parsed.data.description});if(result.error)return{status:"error",message:result.error.code==="42501"?"accessDenied":"invalidFields"};for(const locale of["fr","tr"])revalidatePath(`/${locale}/app/progression`);return{status:"success",message:"created"};}catch{return{status:"error",message:"unexpected"};}}
const ids=(d:FormData,names:readonly string[])=>[...d.keys()].filter(k=>!k.startsWith("$ACTION_")).every(k=>names.includes(k))&&names.every(n=>typeof d.get(n)==="string"&&/^[0-9a-f-]{36}$/iu.test(String(d.get(n))));
async function admin(){const a=await resolveApplicationContext();if(a.status!=="ready"||a.context.role!=="ADMIN")return null;return createServerSupabaseClient();}
function refresh(){for(const l of["fr","tr"])revalidatePath(`/${l}/app/progression`);}
export async function publishOutcomeRevisionAction(outcomeId:string,_:ProgressionActionState,d:FormData):Promise<ProgressionActionState>{if([...d.keys()].some(k=>!k.startsWith("$ACTION_")&&!["title","description"].includes(k))||typeof d.get("title")!=="string"||!String(d.get("title")).trim())return{status:"error",message:"invalidFields"};const c=await admin();if(!c)return{status:"error",message:"accessDenied"};const r=await c.rpc("publish_learning_outcome_revision",{target_outcome_id:outcomeId,outcome_title:String(d.get("title")).trim(),outcome_description:String(d.get("description")??"").trim()});if(r.error)return{status:"error",message:r.error.code==="42501"?"accessDenied":"invalidFields"};refresh();return{status:"success",message:"updated"};}
export async function setOutcomeActiveAction(outcomeId:string,active:boolean,_:ProgressionActionState,d:FormData):Promise<ProgressionActionState>{if([...d.keys()].some(k=>!k.startsWith("$ACTION_")))return{status:"error",message:"invalidFields"};const c=await admin();if(!c)return{status:"error",message:"accessDenied"};const r=await c.rpc("set_learning_outcome_active",{target_outcome_id:outcomeId,target_active:active});if(r.error)return{status:"error",message:"accessDenied"};refresh();return{status:"success",message:"updated"};}
export async function assignOutcomeAction(_:ProgressionActionState,d:FormData):Promise<ProgressionActionState>{if(!ids(d,["classCourseId","revisionId"]))return{status:"error",message:"invalidFields"};const c=await admin();if(!c)return{status:"error",message:"accessDenied"};const r=await c.rpc("assign_outcome_revision",{target_class_course_id:String(d.get("classCourseId")),target_revision_id:String(d.get("revisionId"))});if(r.error)return{status:"error",message:r.error.code==="42501"?"accessDenied":"invalidFields"};refresh();return{status:"success",message:"updated"};}
