"use client";
import { useActionState, useEffect, useId, useRef } from "react";
import { useFormStatus } from "react-dom";
import { initialStructureActionState, type StructureActionState, type StructureField, type StructureMessage } from "./structure";

export type StructureFormMessages = Readonly<{ labels: Record<"name"|"schoolYear"|"code"|"course"|"weeklyPeriods", string>; save: string; saving: string; cancel: string; errors: Record<StructureMessage, string>; }>;
type Action = (state: StructureActionState, data: FormData) => Promise<StructureActionState>;
function Submit({ m }: { m: StructureFormMessages }) { const { pending } = useFormStatus(); return <button className="structure-button structure-button--primary" disabled={pending} type="submit">{pending ? m.saving : m.save}</button>; }
function Feedback({ m, state }: { m: StructureFormMessages; state: StructureActionState }) { return state.message ? <p aria-live="polite" className={`structure-feedback structure-feedback--${state.status}`} role={state.status === "error" ? "alert" : "status"} tabIndex={-1}>{m.errors[state.message]}</p> : null; }
function Field({ children, error, field, id, label, m }: Readonly<{ children?: React.ReactNode; error?: StructureMessage; field: StructureField; id: string; label: string; m: StructureFormMessages }>) { return <div className="structure-field"><label htmlFor={`${id}-${field}`}>{label}</label>{children}{error ? <p className="structure-field__error" id={`${id}-${field}-error`}>{m.errors[error]}</p> : null}</div>; }
function Form({ action, children, m }: Readonly<{ action: Action; children: (id: string, state: StructureActionState) => React.ReactNode; m: StructureFormMessages }>) { const [state, formAction] = useActionState(action, initialStructureActionState); const id = useId(); const ref = useRef<HTMLFormElement>(null); useEffect(() => { if (state.status === "error") ref.current?.querySelector<HTMLElement>('[aria-invalid="true"], .structure-feedback')?.focus(); }, [state]); return <form action={formAction} className="structure-form" noValidate ref={ref}><Feedback m={m} state={state}/>{children(id, state)}<div className="structure-form__actions"><Submit m={m}/><button className="structure-button" onClick={(event) => event.currentTarget.closest("details")?.removeAttribute("open")} type="button">{m.cancel}</button></div></form>; }
function Input({ defaultValue, field, id, m, required=true, state, type="text", min, max }: Readonly<{ defaultValue?: string|number; field: StructureField; id: string; m: StructureFormMessages; required?: boolean; state: StructureActionState; type?: string; min?: number; max?: number }>) { const error=state.fieldErrors?.[field]; return <Field error={error} field={field} id={id} label={m.labels[field === "schoolYearId" ? "schoolYear" : field === "courseId" ? "course" : field]} m={m}><input aria-describedby={error ? `${id}-${field}-error` : undefined} aria-invalid={Boolean(error)} autoComplete="off" defaultValue={defaultValue} id={`${id}-${field}`} max={max} min={min} name={field} required={required} type={type}/></Field>; }

export function ClassForm({ action, initialName, m, years }: Readonly<{ action: Action; initialName?: string; m: StructureFormMessages; years?: readonly {id:string;label:string}[] }>) { return <Form action={action} m={m}>{(id,state)=><><Input defaultValue={initialName} field="name" id={id} m={m} state={state}/>{years ? <Field error={state.fieldErrors?.schoolYearId} field="schoolYearId" id={id} label={m.labels.schoolYear} m={m}><select aria-invalid={Boolean(state.fieldErrors?.schoolYearId)} defaultValue="" id={`${id}-schoolYearId`} name="schoolYearId" required><option disabled value="">—</option>{years.map(y=><option key={y.id} value={y.id}>{y.label}</option>)}</select></Field> : null}</> }</Form>; }
export function CourseForm({ action, initial, m }: Readonly<{ action: Action; initial?: {name:string;code:string|null}; m: StructureFormMessages }>) { return <Form action={action} m={m}>{(id,state)=><><Input defaultValue={initial?.name} field="name" id={id} m={m} state={state}/><Input defaultValue={initial?.code ?? ""} field="code" id={id} m={m} required={false} state={state}/></>}</Form>; }
export function ConnectionForm({ action, courses, m }: Readonly<{ action: Action; courses: readonly {id:string;name:string;code:string|null}[]; m: StructureFormMessages }>) { return <Form action={action} m={m}>{(id,state)=><><Field error={state.fieldErrors?.courseId} field="courseId" id={id} label={m.labels.course} m={m}><select aria-invalid={Boolean(state.fieldErrors?.courseId)} defaultValue="" id={`${id}-courseId`} name="courseId" required><option disabled value="">—</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}{c.code ? ` (${c.code})` : ""}</option>)}</select></Field><Input field="weeklyPeriods" id={id} m={m} max={40} min={1} state={state} type="number"/></>}</Form>; }
export function PeriodsForm({ action, initial, m }: Readonly<{ action: Action; initial:number; m:StructureFormMessages }>) { return <Form action={action} m={m}>{(id,state)=><Input defaultValue={initial} field="weeklyPeriods" id={id} m={m} max={40} min={1} state={state} type="number"/>}</Form>; }
