"use server";
import { revalidatePath } from "next/cache";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { resolveApplicationContext } from "@/server/application-context";
import { mapAssignmentError,parseCreateAssignment,parseUpdateAssignment,validAssignmentId,type AssignmentActionState } from "./assignment";
async function context(){const access=await resolveApplicationContext();if(access.status!=="ready"||access.context.role!=="ADMIN")return null;return{schoolId:access.context.school.id,supabase:await createServerSupabaseClient()};}
function refresh(classId:string){for(const locale of ["fr","tr"] as const){revalidatePath(`/${locale}/app/classes/${classId}`);revalidatePath(`/${locale}/app/mes-classes`);}}
export async function createAssignmentAction(classId:string,classCourseId:string,_:AssignmentActionState,data:FormData):Promise<AssignmentActionState>{if(!validAssignmentId(classId)||!validAssignmentId(classCourseId))return{status:"error",message:"targetUnavailable"};const parsed=parseCreateAssignment(data);if(!parsed.ok)return parsed.state;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const target=await ctx.supabase.from("class_courses").select("id").eq("id",classCourseId).eq("class_id",classId).eq("school_id",ctx.schoolId).eq("is_active",true).maybeSingle();if(target.error||!target.data)return{status:"error",message:"targetUnavailable"};const result=await ctx.supabase.rpc("admin_create_teacher_assignment",{target_teacher_id:parsed.data.teacherId,target_class_course_id:classCourseId,assigned_weekly_periods:parsed.data.weeklyPeriods});if(result.error)return{status:"error",message:mapAssignmentError(result.error)};refresh(classId);return{status:"success",message:"assignmentCreated"};}catch{return{status:"error",message:"unexpected"};}}
export async function updateAssignmentAction(classId:string,assignmentId:string,nextActive:boolean,_:AssignmentActionState,data:FormData):Promise<AssignmentActionState>{if(!validAssignmentId(classId)||!validAssignmentId(assignmentId))return{status:"error",message:"targetUnavailable"};const parsed=parseUpdateAssignment(data,nextActive);if(!parsed.ok)return parsed.state;try{const ctx=await context();if(!ctx)return{status:"error",message:"accessDenied"};const target=await ctx.supabase.from("teacher_assignments").select("id").eq("id",assignmentId).eq("school_id",ctx.schoolId).maybeSingle();if(target.error||!target.data)return{status:"error",message:"targetUnavailable"};const result=await ctx.supabase.rpc("admin_update_teacher_assignment",{target_assignment_id:assignmentId,assigned_weekly_periods:parsed.data.weeklyPeriods,assignment_is_active:nextActive});if(result.error)return{status:"error",message:mapAssignmentError(result.error)};refresh(classId);return{status:"success",message:"assignmentUpdated"};}catch{return{status:"error",message:"unexpected"};}}
